obophenotype/bio-attribute-ontology

src/patterns/data/default/chemical_role_attribute.tsv, src/patterns/data/default/chemical_role_attribute_location.tsv, src/patterns/data/default/entity_attribute.tsv, src/patterns/data/default/entity_attribute_location.tsv, src/patterns/dosdp-patterns/chemical_role_attribute.yaml, src/patterns/dosdp-patterns/chemical_role_attribute_location.yaml
=> Add patterns needed for chemical roles.

src/patterns/data/default/disease_onset.tsv
This commit intends to
add [this table](https://docs.google.com/spreadsheets/d/1UiCa1XjLy1LAz-mnGuplb754DqzJjO9YlZ6eeS19uKY/edit#gid=1204072197) as a `tsv` to  `src/patterns/data/default`.
If applied, this commit will fix #49.
=> Add `disease_onset.tsv`

src/patterns/data/default/attribute_location.tsv, src/patterns/data/default/entity_attribute.tsv
=> Fix logical definition for ‘body fluid levels’.

src/mappings/oba-efo.sssom.tsv, src/mappings/oba-vt.sssom.tsv
This commit is related to #85 and #101.
=> Sync sssom tsv tables with google sheet data

src/patterns/data/default/response_to_chemical_stimulus_trait.tsv
This commit is related to #85 to import VT terms into OBA.
=> Update response to chemical stimulus data table

src/ontology/components/synonyms.owl, src/templates/synonyms.owl, src/templates/synonyms.tsv
=> adding chest girth synonym

src/patterns/data/default/disease_onset.tsv, src/patterns/dosdp-patterns/disease_onset.yaml
1. Update labels in data table and
2. add new classes as requested by https://github.com/EBISPOT/efo/issues/1693 .
3. Update ORCID comments and fix yaml syntax in `disease_onset.yaml`.
If applied, this commit will fix #111.
=> Add new disease onset terms

src/ontology/components/measured_in.owl, src/ontology/components/obsoletes.owl, src/ontology/components/synonyms.owl, src/patterns/data/default/entity_attribute.tsv, src/templates/replaced.owl, src/templates/replaced.tsv
1. Fix [OBA:0004273.](https://www.ebi.ac.uk/ols/ontologies/oba/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBA_0004273)
Replace [GO:0007569 obsolete cell aging](https://www.ebi.ac.uk/QuickGO/term/GO:0007569) with [GO:0090398 cellular senescence](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0090398) in `entity_attribute.tsv`.
2. Obsolete [OBA:1000815.](https://www.ebi.ac.uk/ols/ontologies/oba/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBA_1000815)
This commit is related to #118.
=> Fix obsolete GO terms

src/ontology/components/synonyms.owl, src/templates/synonyms.owl, src/templates/synonyms.tsv
=> add synonyms to trait terms

src/patterns/data/default/entity_attribute.tsv, src/patterns/data/default/entity_attribute_location.tsv
This commit intends to
add new entity_attribute_location traits related to PATO:0000025 composition. 
Part of #85.
=> Add new composition traits

src/patterns/data/default/entity_attribute_location.tsv
Attribute: PATO:0000070	amount
OBA:VT0010481
OBA:VT0008616
OBA:VT0010710
OBA:VT0010480
OBA:VT0010477
OBA:VT0001805
OBA:VT0010535
OBA:VT0010513
OBA:VT0008498
OBA:VT0010919
OBA:VT0001553
OBA:VT0010808
OBA:VT0000199
OBA:VT0010918
OBA:VT0010711
OBA:VT0005567
OBA:VT0002492
OBA:VT0008497
OBA:VT0010694
OBA:VT0005265
OBA:VT0001573
OBA:VT0003065
OBA:VT0001807
OBA:VT0010545
OBA:VT0010878
OBA:VT0010677
OBA:VT0010648
OBA:VT0008495
OBA:VT0002871
OBA:VT1000047
OBA:VT0010616
OBA:VT0010695
OBA:VT0008897
OBA:VT0010474
OBA:VT0000203
OBA:VT0005119
OBA:VT0008550
OBA:VT0008496
OBA:VT0003457
OBA:VT0010476
OBA:VT0010540
Part of #85.
=> Add 41 new entity_attribute_location terms

src/patterns/data/default/entity_attribute.tsv, src/patterns/data/default/entity_attribute_location.tsv
This commit intends to
1. Add VT pigmentation terms OBA:VT0002095 OBA:VT0005102 OBA:VT0010463.
2. Add VT 'content' term OBA:VT0010714.
Part of #85.
=> Add VT pigmentation and content terms

src/mappings/oba-vt.sssom.tsv, src/patterns/data/default/entity_attribute.tsv
1. VT:0007075	heart left ventricle wall thickness
2. VT:0007088	heart right ventricle wall thickness
3. VT:0007086	heart ventricle septum thickness
Part of #85.
=> Add VT thickness terms

src/patterns/data/default/entity_attribute.tsv
Addresses EFO_OBA mapping issue #150 
I added 3 of the 7 EFO diameter terms using the DOSDP pattern entity_attribute.tsv file. _(Need to discuss the other terms)_ 
EFO:0021787	ascending aorta diameter
EFO:0021788	descending aorta diameter
EFO:0021786	aorta diameter
=> Added 3 (cardiac vessels) EFO diameter terms

src/patterns/data/default/disease_onset.tsv
=> Add new term `age of onset of cervical dystonia`

src/scripts/oba-mpd-doids-comparison.Rmd, src/scripts/oba-mpd-doids.Rmd, src/scripts/oba-mpd.Rmd
Analysis files that examine 1) coverage of OBA VT terms in MPD (oba-mpd) 2) DOID to VT terms via 2 approaches (oba-mpd-doids) and 3) a comparison of the DOID to VT approaches (oba-mpd-doids-comparison)
=> Added MPD-OBA Rmd scripts

src/ontology/oba-idranges.owl
I would like to request a block of IDs for NTRs. Thank you.
=> ID range request

src/patterns/data/default/disease_onset.tsv
=> added new term 'age of onset of anorexia nervosa'

src/ontology/components/obsoletes.owl, src/ontology/components/synonyms.owl, src/ontology/oba-edit.obo, src/ontology/oba-odk.yaml, src/patterns/data/default/entity_attribute.tsv
fixes #191
@ehartley can you check we didn't accidentally add duplicates? EDIT: don't worry lets see if QC complains.
=> Add new OBA classes for COA

docs/oba-release-sop.md
Add previously missing steps to SOP.
=> Update release SOP document

src/patterns/data/default/entity_attribute_location.tsv
This commit intends to add new chemical entity amount in location traits to address https://github.com/EBISPOT/efo/issues/1882.
If applied, this commit will fix #245.
=> Add new chemical entity amount in location traits

src/ontology/components/obsoletes.owl, src/ontology/components/synonyms.owl, src/patterns/data/default/entity_attribute_location.tsv
This commit intends to add 4737 new `level of XXX-PROTEIN in blood serum` trait terms. If applied, this commit will fix #222 and addresses https://github.com/EBISPOT/efo/issues/1848
=> Add level of protein in blood serum traits

src/ontology/components/obsoletes.owl, src/ontology/components/synonyms.owl, src/ontology/oba-edit.obo, src/patterns/data/default/entity_attribute.tsv, src/patterns/data/default/entity_attribute_location.tsv
Update some lipid trait term labels.
Add new level of lipid in blood serum trait terms.
If applied, this is part of a series to fix #257.
Addresses https://github.com/EBISPOT/efo/issues/1905 
Addresses https://github.com/EBISPOT/efo/issues/1924
=> Add lipid trait terms for GWAS/EFO

src/patterns/data/default/entity_attribute_location.tsv
=> Added new OBA protein terms + refreshed imports

src/mappings/oba-efo-mapping-exclusions.sssom.tsv, src/mappings/oba-efo.sssom.tsv, src/mappings/oba-vt.sssom.tsv
=> Update SSSOM mapping files

src/ontology/components/obsoletes.owl, src/ontology/components/synonyms.owl, src/patterns/data/default/entity_attribute_location.tsv
1. Add new lipid level term.
2. Replace SLM component with CHEBI term where CHEBI term available in logical axioms.
Addresses https://github.com/EBISPOT/efo/issues/1882#issuecomment-1638416837 .
=> Update lipid level traits

src/patterns/data/default/disease_onset.tsv
=> Added new 'age of onset' term

src/patterns/data/default/entity_attribute_location.tsv
- for **GWAS** **lipid** term request '13,16,19-**Docosatrienoic** acid measurement' **[EFO issue 1905](https://github.com/EBISPOT/efo/issues/1905)**
=> Added new OBA term + update imports

src/ontology/components/obsoletes.owl, src/ontology/components/synonyms.owl, src/patterns/data/default/response_to_chemical_stimulus_trait.tsv
=> Added new 'response to' term + updated imports

src/ontology/components/obsoletes.owl, src/ontology/components/synonyms.owl, src/patterns/data/default/entity_attribute_location.tsv
- issue https://github.com/EBISPOT/efo/issues/2045
=> Add sputum amount terms gwas

src/patterns/data/default/response_to_chemical_stimulus_trait.tsv
=> Added new 'response to' term

src/patterns/data/default/entity_attribute_location.tsv
- added 4 new OBA terms for https://github.com/EBISPOT/efo/issues/2079
=> Added new 'protein amount in plasma' terms

src/patterns/data/default/entity_attribute_location.tsv
- oxylipin terms for issue https://github.com/EBISPOT/efo/issues/2059
=> Added lipid terms

src/patterns/data/default/entity_attribute.tsv, src/patterns/data/default/entity_attribute_location.tsv, src/patterns/data/default/response_to_chemical_with_role_stimulus.tsv
=> Add clinical measurement related traits

src/patterns/data/default/entity_attribute.tsv
-issue https://github.com/EBISPOT/efo/issues/2116
=> Added synonym + reference

docs/cite.md, docs/oba-release-sop.md
- fix some formatting issues
- bring SOP content up to date
- reorganise SOP to make it less confusing
=> Fix documents

src/patterns/data/default/entity_attribute.tsv
- issue https://github.com/EBISPOT/efo/issues/2152
=> Added new trait term

src/patterns/data/default/chemical_role_attribute_location.tsv, src/patterns/data/default/entity_attribute_location.tsv
- addresses issue https://github.com/EBISPOT/efo/issues/2184
=> Added new chemical level term

src/patterns/data/default/entity_attribute_location.tsv
- issue https://github.com/EBISPOT/efo/issues/2222
=> Added protein terms_2

src/patterns/data/default/entity_attribute_location.tsv
Added 1 term for ticket https://github.com/EBISPOT/efo/issues/2245
=> Added protein terms_4

src/patterns/data/default/entity_attribute.tsv, src/patterns/data/default/entity_attribute_part_of.tsv, src/patterns/data/default/response_to_chemical_stimulus_trait.tsv
Related to issue: https://github.com/EBISPOT/efo/issues/2288
=> NTR: response_to_gabapentin

src/patterns/data/default/entity_attribute_location.tsv
- related to issue https://github.com/EBISPOT/efo/issues/2309
=> Added NTR_protein_level

src/patterns/data/default/entity_attribute_location.tsv
Caused the whole world come crushing down
=> Redundant pipe in pattern

src/patterns/data/default/response_to_chemical_with_role_stimulus.tsv
The purpose of this PR is to add new CHEBI chemical role terms to improve the grouping and hierarchy of composite trait terms.
=> Add new chemical role terms

src/patterns/data/default/attribute_location.tsv, src/patterns/data/default/entity_attribute_location.tsv
- issue https://github.com/EBISPOT/efo/issues/2356
- added 4 skin terms
=> Added new skin terms for GWAS

src/patterns/data/default/entity_attribute_part_of.tsv
-Related to issue https://github.com/EBISPOT/efo/issues/2387
=> Added NTR enzyme activity
